//
//  CalculatorPresenter.swift
//  ConcurrencyOneMinute
//
//  Created by Papon Supamongkonchai on 20/4/2566 BE.
//  Copyright (c) 2566 BE ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol CalculatorPresentationLogic
{
    func presentCalculateResult(response: Calculator.RatePerBTC)
    func presentSetCurrencyNameConvert(coinName: String)
}

class CalculatorPresenter: CalculatorPresentationLogic
{
    weak var viewController: CalculatorDisplayLogic?
    
    // MARK: CalculatorPresentationLogic
    
    func presentCalculateResult(response: Calculator.RatePerBTC) {
        let viewModel = Calculator.DisplayResultCalcutor(resultCalcutor: response.resultCalcutor)
        viewController?.displayCalculateResult(viewModel: viewModel)
    }
    
    func presentSetCurrencyNameConvert(coinName: String) {
        viewController?.displaySetCurrencyNameConvert(coinName: coinName)
    }
}
