//
//  CalculatorViewController.swift
//  ConcurrencyOneMinute
//
//  Created by Papon Supamongkonchai on 20/4/2566 BE.
//  Copyright (c) 2566 BE ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol CalculatorDisplayLogic: AnyObject
{
    func displayCalculateResult(viewModel: Calculator.DisplayResultCalcutor)
    func displaySetCurrencyNameConvert(currencyRatePerBTC: CurrencyRatePerBTC?)
}

class CalculatorViewController: UIViewController, CalculatorDisplayLogic
{
    //MARK: Property View
    @IBOutlet weak var nameConcurrencyLabel: UILabel!
    @IBOutlet weak var resultCalculateLabel: UILabel!
    @IBOutlet weak var calculatorPerBTCTextField: UITextField!
    
    //MARK: Property Control & Data
    var interactor: CalculatorBusinessLogic?
    var router: (NSObjectProtocol & CalculatorRoutingLogic & CalculatorDataPassing)?
    
    //MARK: setup
    override func awakeFromNib() {
        super.awakeFromNib()
        let config = CalculatorConfigutrator()
        config.configure(viewController: self)
    }
    
    // MARK: View lifecycle
    override func viewDidLoad()
    {
        super.viewDidLoad()
        setupView()
        self.interactor?.setCurrencyNameConvert()
    }
    
    // MARK: View
    private func setupView() {
        calculatorPerBTCTextField.delegate = self
        calculatorPerBTCTextField.addTarget(self, action: #selector(textFieldDidChange(_:)), for: .editingChanged)
    }
    
    // MARK: Function
    func getResultRateBTC(btc: String) {
        let numberBTC = Double(btc) ?? 0.0
        interactor?.calculateResult(numberBTC: numberBTC)
    }
    
    // MARK: CalculatorDisplayLogic
    func displayCalculateResult(viewModel: Calculator.DisplayResultCalcutor) {
        self.resultCalculateLabel.text = viewModel.resultCalcutor.toCurrencyString()
    }
    
    func displaySetCurrencyNameConvert(currencyRatePerBTC: CurrencyRatePerBTC?) {
        if let currencyRatePerBTC = currencyRatePerBTC {
            self.nameConcurrencyLabel.text = "\(currencyRatePerBTC.nameCoin) : \(currencyRatePerBTC.rateCoinPerBTC)"
        }
        
    }
}

extension CalculatorViewController : UITextFieldDelegate {
    func textFieldDidEndEditing(_ textField: UITextField) {
        self.getResultRateBTC(btc: textField.text ?? "")
    }
    
    @objc func textFieldDidChange(_ textField: UITextField) {
        self.getResultRateBTC(btc: textField.text ?? "")
    }
}
