//
//  CalculatorInteractor.swift
//  ConcurrencyOneMinute
//
//  Created by Papon Supamongkonchai on 20/4/2566 BE.
//  Copyright (c) 2566 BE ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol CalculatorBusinessLogic
{
    func calculateResult(numberBTC: Double)
    func setCurrencyNameConvert()
}

protocol CalculatorDataStore
{
    var currencyRatePerBTC: CurrencyRatePerBTC? { get set }
}

class CalculatorInteractor: CalculatorBusinessLogic, CalculatorDataStore
{
    var presenter: CalculatorPresentationLogic?
    var worker: CalculatorWorker = CalculatorWorker()
    
    var currencyRatePerBTC: CurrencyRatePerBTC? = nil
    
    // MARK: CalculatorBusinessLogic
    func calculateResult(numberBTC: Double) {
        let response = Calculator.RatePerBTC(currencyRatePerBTC: currencyRatePerBTC, numberBTC: numberBTC)
        presenter?.presentCalculateResult(response: response)
    }
    
    func setCurrencyNameConvert() {
        presenter?.presentSetCurrencyNameConvert(coinName: currencyRatePerBTC?.nameCoin ?? "")
    }
}
