//
//  CalculatorModels.swift
//  ConcurrencyOneMinute
//
//  Created by Papon Supamongkonchai on 20/4/2566 BE.
//  Copyright (c) 2566 BE ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum Calculator
{
    // MARK: Use cases
    
    struct RatePerBTC
    {
        var currencyRatePerBTC: CurrencyRatePerBTC?
        var numberBTC: Double
        var resultCalcutor: Double {
            return (currencyRatePerBTC?.rateCoinPerBTC ?? 0.0) * numberBTC
        }
    }
    
    struct DisplayResultCalcutor {
        var resultCalcutor: Double
    }
}

struct CurrencyRatePerBTC {
    var rateCoinPerBTC: Double
    var nameCoin: String 
}
