//
//  HistoryInteractor.swift
//  ConcurrencyOneMinute
//
//  Created by Papon Supamongkonchai on 20/4/2566 BE.
//  Copyright (c) 2566 BE ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol HistoryBusinessLogic
{
    func getHistoryCoinAssets()
}

protocol HistoryDataStore
{
    
}

class HistoryInteractor: HistoryBusinessLogic, HistoryDataStore
{
    var presenter: HistoryPresentationLogic?
    var worker: HistoryWorker = HistoryWorker()
    
    // MARK: Do something
    
    func getHistoryCoinAssets() {
        worker.getPriceDataInHistory { assetPrices in
            let response = History.PriceAsset.ViewModel(pricesDisplayModel: assetPrices)
            self.presenter?.presentGetHistoryCoinAssets(response: response)
        }
        
    }
}
