//
//  HistoryWorker.swift
//  ConcurrencyOneMinute
//
//  Created by Papon Supamongkonchai on 20/4/2566 BE.
//  Copyright (c) 2566 BE ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol HistoryWorkerInterface {
    func getPriceDataInHistory(success:@escaping () -> Void)
}

class HistoryWorker
{
    func getPriceDataInHistory(success:@escaping ([PriceDisplayModel]) -> Void) {
        let pricesHistory = LocalDataManager.shared.getPricesBPI()
        success(pricesHistory)
    }
}
