//
//  HistoryViewController.swift
//  ConcurrencyOneMinute
//
//  Created by Papon Supamongkonchai on 20/4/2566 BE.
//  Copyright (c) 2566 BE ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol HistoryDisplayLogic: AnyObject
{
    func displaySomething(viewModel: History.Something.ViewModel)
}

class HistoryViewController: UIViewController, HistoryDisplayLogic
{
    var interactor: HistoryBusinessLogic?
    var router: (NSObjectProtocol & HistoryRoutingLogic & HistoryDataPassing)?
    
    //MARK: setup
    override func awakeFromNib() {
        super.awakeFromNib()
        let config = HistoryConfigurator()
        config.configure(viewController: self)
    }
    
    // MARK: View lifecycle
    
    override func viewDidLoad()
    {
        super.viewDidLoad()
        let list = LocalDataManager.shared.getPricesBPI()
        print(list)
        doSomething()
    }
    
    // MARK: Do something
    
    //@IBOutlet weak var nameTextField: UITextField!
    
    func doSomething()
    {
        let request = History.Something.Request()
        interactor?.doSomething(request: request)
    }
    
    func displaySomething(viewModel: History.Something.ViewModel)
    {
        //nameTextField.text = viewModel.name
    }
}
