//
//  HomeRouter.swift
//  ConcurrencyOneMinute
//
//  Created by Papon Supamongkonchai on 20/4/2566 BE.
//  Copyright (c) 2566 BE ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol HomeRoutingLogic
{
    func routeToHistoryView()
    func routeToCalculateView()
}

protocol HomeDataPassing
{
    var dataStore: HomeDataStore? { get }
}

class HomeRouter: NSObject, HomeRoutingLogic, HomeDataPassing
{
    weak var viewController: HomeViewController?
    var dataStore: HomeDataStore?
    
    // MARK: Routing
    
    func routeToHistoryView() {
        let storyboard = UIStoryboard(name: "HistoryStoryboard", bundle: nil)
        let destinationVC = storyboard.instantiateViewController(withIdentifier: "HistoryViewController") as! HistoryViewController
        navigateToHistoryView(source: viewController!, destination: destinationVC)
    }
    
    func routeToCalculateView() {
        let storyboard = UIStoryboard(name: "CalculatorStoryboard", bundle: nil)
        let destinationVC = storyboard.instantiateViewController(withIdentifier: "CalculatorViewController") as! CalculatorViewController
        var destinationDS = destinationVC.router!.dataStore!
        passDataToCalculatorView(source: dataStore!, destination: &destinationDS)
        navigateToCalculatorView(source: viewController!, destination: destinationVC)
    }
    
    // MARK: Navigation
    func navigateToHistoryView(source: HomeViewController, destination: HistoryViewController) {
        destination.modalPresentationStyle = .fullScreen
        source.navigationController?.pushViewController(destination, animated: true)
    }
    
    func navigateToCalculatorView(source: HomeViewController, destination: CalculatorViewController) {
        destination.modalPresentationStyle = .fullScreen
        source.navigationController?.pushViewController(destination, animated: true)
    }
    
    // MARK: Passing data
    func passDataToCalculatorView(source: HomeDataStore, destination: inout CalculatorDataStore) {
        destination.currencyRatePerBTC = source.currencyRatePerBTC
    }
}
