//
//  HomeRouter.swift
//  ConcurrencyOneMinute
//
//  Created by Papon Supamongkonchai on 20/4/2566 BE.
//  Copyright (c) 2566 BE ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol HomeRoutingLogic
{
    func routeToHistoryView()
}

protocol HomeDataPassing
{
    var dataStore: HomeDataStore? { get }
}

class HomeRouter: NSObject, HomeRoutingLogic, HomeDataPassing
{
    weak var viewController: HomeViewController?
    var dataStore: HomeDataStore?
    
    // MARK: Routing
    
    func routeToHistoryView()
    {
        let storyboard = UIStoryboard(name: "HistoryStoryboard", bundle: nil)
        let destinationVC = storyboard.instantiateViewController(withIdentifier: "HistoryViewController") as! HistoryViewController
//        var destinationDS = destinationVC.router!.dataStore!
//        passDataToHistoryView(source: dataStore!, destination: &destinationDS)
        navigateToHistoryView(source: viewController!, destination: destinationVC)
    }
    
    // MARK: Navigation
    
    func navigateToHistoryView(source: HomeViewController, destination: HistoryViewController) {
        destination.modalPresentationStyle = .fullScreen
        source.navigationController?.pushViewController(destination, animated: true)
    }
    
    // MARK: Passing data
    
//    func passDataToHistoryView(source: HomeDataStore, destination: inout HistoryDataStore) {
//      destination.name = source.name
//    }
}
