//
//  HomeModels.swift
//  ConcurrencyOneMinute
//
//  Created by Papon Supamongkonchai on 20/4/2566 BE.
//  Copyright (c) 2566 BE ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum Home
{
    // MARK: Use cases
    enum PriceAsset
    {
        struct Request
        {
            
        }
        struct Response
        {
            var timeUpdate: String
            var prices: [String: Currency]
        }
        struct ViewModel
        {
            var pricesDisplayModel: [PriceDisplayModel]
        }
    }
}

struct PriceDisplayModel: Codable {
    var nameCoin: String
    var priceCoin: String
    var time: String

    enum CodingKeys: String, CodingKey {
        case nameCoin = "name_coin"
        case priceCoin = "price_coin"
        case time
    }

    var dictionaryRepresentation: [String: Any] {
        return [
            "name_coin": nameCoin,
            "price_coin": priceCoin,
            "time": time
        ]
    }
    
    var propertyListRepresentation: [Any] {
        return [
            nameCoin,
            priceCoin,
            time
        ]
    }
}
