//
//  HomeInteractor.swift
//  ConcurrencyOneMinute
//
//  Created by Papon Supamongkonchai on 20/4/2566 BE.
//  Copyright (c) 2566 BE ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol HomeBusinessLogic
{
    func getPriceCoin(request: Home.PriceAsset.Request)
}

protocol HomeDataStore
{
    //var name: String { get set }
}

class HomeInteractor: HomeBusinessLogic, HomeDataStore
{
    var presenter: HomePresentationLogic?
    var worker: HomeWorker = HomeWorker(service: HomeService())
    //var name: String = ""
    
    // MARK: Do something
    
    func getPriceCoin(request: Home.PriceAsset.Request)
    {
        worker.getCurrentPriceCoin { response in
            self.presenter?.presentGetPriceCoin(response: response)
        } fail: { error in
            print("Error getPriceCoin : \(error?.description)")
        }
    }
}
